nodeLinker: pnp
pnpMode: loose

yarnPath: .yarn/releases/yarn-3.6.1.cjs

packageExtensions:
  "@fluentui/react-field@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-input@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-alert@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-tree@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-persona@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-infobutton@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-table@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-toolbar@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-checkbox@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-dialog@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-drawer@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-progress@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-select@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-skeleton@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-slider@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-spinbutton@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-switch@*":
    peerDependencies:
      scheduler: ^0.20.0
  "@fluentui/react-textarea@*":
    peerDependencies:
      scheduler: ^0.20.0

